### ISSUE TITLE
Sharpie tool does not create bindings on latest iOS SDK

### ISSUE THREAD

**Issue by Leo506** [dotnet/macios#22622]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0.100

### Description

When I'm trying to use sharpie tools for generating ApiDefinications and StructsAndEnums I'm getting a lot of errors:
```
Parsing 1 header files...
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_ptrdiff_t.h:41:10: note: submodule of top-level module '_stddef' implicitly imported here
   41 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_size_t.h:40:10: note: submodule of top-level module '_stddef' implicitly imported here
   40 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_wchar_t.h:41:10: note: submodule of top-level module '_stddef' implicitly imported here
   41 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from <module-includes>:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/machine/endian.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/arm/endian.h:61:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_endian.h:131:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/libkern/_OSByteOrder.h:32:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types.h:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/machine/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/arm/_types.h:75:9: error: unknown type name 'ptrdiff_t'
   75 | typedef ptrdiff_t               __darwin_ptrdiff_t;     /* ptr1 - ptr2 */
      |         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/arm/_types.h:85:9: error: unknown type name 'size_t'
   85 | typedef size_t                  __darwin_size_t;        /* sizeof() */
      |         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/arm/_types.h:101:9: error: unknown type name 'wchar_t'
  101 | typedef wchar_t                 __darwin_wchar_t;       /* wchar_t */
      |         ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_null.h:40:10: note: submodule of top-level module '_stddef' implicitly imported here
   40 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_offsetof.h:40:10: note: submodule of top-level module '_stddef' implicitly imported here
   40 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'DarwinFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/module.modulemap:45:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/c_standard_library.modulemap:313:8: error: module '_stddef' requires feature 'found_incompatible_headers__check_search_paths'
  313 | module _stddef [system] {
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_rsize_t.h:40:10: note: submodule of top-level module '_stddef' implicitly imported here
   40 | #include <stddef.h>
      |          ^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:72:10: fatal error: could not build module 'DarwinFoundation'
   72 | #include <sys/appleapiopts.h>
      |  ~~~~~~~~^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module 'netinet_in' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:113:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_in_addr_t.h:30:10: fatal error: could not build module 'DarwinFoundation'
   30 | #include <machine/types.h> /* __uint32_t */
      |  ~~~~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_useconds_t.h:30:10: fatal error: could not build module 'DarwinFoundation'
   30 | #include <sys/_types.h> /* __darwin_useconds_t */
      |  ~~~~~~~~^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module '_errno' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:178:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/errno.h:23:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/errno.h:72:10: fatal error: could not build module 'DarwinFoundation'
   72 | #include <sys/cdefs.h>
      |  ~~~~~~~~^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
While building module '_sys_select' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/types.h:187:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/sys/_types/_fd_def.h:31:10: fatal error: could not build module 'DarwinFoundation'
   31 | #include <machine/types.h> /* __int32_t and uintptr_t */
      |  ~~~~~~~~^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:10: fatal error: could not build module 'sys_types'
   18 | #include <sys/types.h>
      |  ~~~~~~~~^
While building module 'Lottie' imported from /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h:1:
While building module 'Foundation' imported from /Users/arbusbiz/Library/Developer/Xcode/DerivedData/Lottie-cnzddmjaatpbkchkmdixmnubilje/Build/Products/Lottie.iOS.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h:28:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
While building module '_assert' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/assert.h:58:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_assert.h:45:10: fatal error: could not build module 'DarwinFoundation'
   45 | #include <sys/cdefs.h>
      |  ~~~~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_ctype.h:70:10: fatal error: could not build module 'DarwinFoundation'
   70 | #include <sys/cdefs.h>
      |  ~~~~~~~~^

Binding...
74 errors generated.
Error while processing /private/var/folders/cq/s08_xkrn06bdj5qls0ytdbzc0000gn/T/com.xamarin.ObjectiveSharpie/ad35dc27c1f745cfa59dd2aa9091133e.h.

Done. Exiting with error code 1.
error: Clang failed to parse input and exited with code 1
```

### Steps to Reproduce

1. Build framework with iphoneos18.4 SDK (Xcode 16.3)
2. Run sharpie (3.5.116) command:
```
sharpie bind \
-sdk iphoneos18.4 \
-framework ./Lottie.iOS.xcframework/ios-arm64/Lottie.framework
```

**Comment by JamesRen0717** [comment]
getting the same issues with .NET 8.0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.408/

.NET workloads installed:
 [maui-ios]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.100/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.100/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.400
   Manifest Version:    8.0.100/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.100/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.15
  Architecture: arm64

.NET SDKs installed:
  8.0.408 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by rolfbjarne** [comment]
I can reproduce this; it might require us to update to a newer version of clang in sharpie. This work is in progress alreaedy, but it's a significant amount of work, so it may take a while until it's done.

**Comment by cho-trackman** [comment]
Does that also mean that Sharpie will no longer need Xamarin.iOS?

**Comment by rolfbjarne** [comment]
Yes, eventually.

**Comment by tompi** [comment]
This last comment kind of made me wanna cry, struggling to update this to latest:

https://github.com/Laerdal/Xamarin.AzureCommunicationCalling/blob/maui-beta/Bindings/Laerdal.Maui.AzureCommunicationCalling.iOS/ApiDefinitions.cs

**Comment by AdamEssenmacher** [comment]
Does anyone happen to know what the last working version of XCode was for Sharpie? If it works on some version of 16.* this isn't really a big deal, but if we need 15 that's a problem with Sequoia...

**Comment by cho-trackman** [comment]
> [@rolfbjarne](https://github.com/rolfbjarne) Is there a workaround for this? we need to publish the ios app but this is blocking. Thanks

Just do `sharpie bind --sdk=iphoneos18.1`

**Comment by Sgudipu** [comment]
@cho-trackman  I have tried with your comment but I am getting like this kind of  error: invalid SDK 'iphoneos18.1'

**Comment by cho-trackman** [comment]
> [@cho-trackman](https://github.com/cho-trackman) I have tried with your comment but I am getting like this kind of error: invalid SDK 'iphoneos18.1'

You obviously need the iOS 18.1 SDK (as a part of Xcode 16.1) installed for that to work. Use https://www.xcodes.app

**Comment by tompi** [comment]
@cho-trackman I think you are misunderstanding the problem, sharpie is NOT compatible with latest iphoneos. I tried with  -sdk iphoneos18.5 and got the same errors as original poster. @Sgudipu if you want to find which iphoneos, just do "xcodebuild -showsdks", but i suspect you will get errors if its 18.something...

I guess I will need to install an older xcode version :(
(I think it worked with 16.1 at least?)

**Comment by cho-trackman** [comment]
> [@cho-trackman](https://github.com/cho-trackman) I think you are misunderstanding the problem, sharpie is NOT compatible with latest iphoneos. I tried with -sdk iphoneos18.5 and got the same errors as original poster. [@Sgudipu](https://github.com/Sgudipu) if you want to find which iphoneos, just do "xcodebuild -showsdks", but i suspect you will get errors if its 18.something...
> 
> I guess I will need to install an older xcode version :( (I think it worked with 16.1 at least?)

I understand the original issue, I was just suggesting a workaround that @ctigrisht was asking for :)

**Comment by tompi** [comment]
@cho-trackman Ah, ok, so you mean 18.1 should work, and that means we should install xcode version 16.1? Perhaps this is a clang 16->17 issue, so xcode 16.2 might also work?

**Comment by cho-trackman** [comment]
> [@cho-trackman](https://github.com/cho-trackman) Ah, ok, so you mean 18.1 should work, and that means we should install xcode version 16.1? Perhaps this is a clang 16->17 issue, so xcode 16.2 might also work?

Maybe Xcode 16.2 will work, I didn't try.

Currently our README.md looks like this:

## Requirements
_Last updated: 2025-05-22_

- __Xcode 16.3 + iOS 18.4 SDKs__ (2025-03-31)
Install with [Xcodes.app](https://github.com/XcodesOrg/XcodesApp): `brew install --cask xcodes`

- __Xcode 16.1 + iOS 18.1 SDKs__ to support Sharpie until https://github.com/dotnet/macios/issues/22622 has been resolved
Install with [Xcodes.app](https://github.com/XcodesOrg/XcodesApp): `brew install --cask xcodes`

- __dotnet 9.0.300__
Check by: `dotnet --list-sdks`
Update with: `brew install --cask dotnet-sdk9-0-300`

- __dotnet iOS workload 18.4.9289__
Check by: `dotnet workload --info`
Update with: `sudo dotnet workload update` (run outside project dir or add `--ignore-failed-sources`)

- __Sharpie 3.5.116__
Check by: `sharpie --version`
Update with: `brew install --cask objectivesharpie`

- __Xamarin iOS SDK 16.4.0.23__
Check by: `readlink /Library/Frameworks/Xamarin.iOS.framework/Versions/Current`
Update with: `brew install --cask xamarin-ios`

**Comment by tompi** [comment]
Thank you @cho-trackman , just tested xcode 16.2 with iphoneos18.2, and that seems to work also!

**Comment by JamesRen0717** [comment]
> > [@cho-trackman](https://github.com/cho-trackman) Ah, ok, so you mean 18.1 should work, and that means we should install xcode version 16.1? Perhaps this is a clang 16->17 issue, so xcode 16.2 might also work?
> 
> Maybe Xcode 16.2 will work, I didn't try.
> 
> Currently our README.md looks like this:
> 
> ## Requirements
> _Last updated: 2025-05-22_
> 
> * **Xcode 16.3 + iOS 18.4 SDKs** (2025-03-31)
>   Install with [Xcodes.app](https://github.com/XcodesOrg/XcodesApp): `brew install --cask xcodes`
> * **Xcode 16.1 + iOS 18.1 SDKs** to support Sharpie until [Sharpie tool does not create bindings on latest iOS SDK #22622](https://github.com/dotnet/macios/issues/22622) has been resolved
>   Install with [Xcodes.app](https://github.com/XcodesOrg/XcodesApp): `brew install --cask xcodes`
> * **dotnet 9.0.300**
>   Check by: `dotnet --list-sdks`
>   Update with: `brew install --cask dotnet-sdk9-0-300`
> * **dotnet iOS workload 18.4.9289**
>   Check by: `dotnet workload --info`
>   Update with: `sudo dotnet workload update` (run outside project dir or add `--ignore-failed-sources`)
> * **Sharpie 3.5.116**
>   Check by: `sharpie --version`
>   Update with: `brew install --cask objectivesharpie`
> * **Xamarin iOS SDK 16.4.0.23**
>   Check by: `readlink /Library/Frameworks/Xamarin.iOS.framework/Versions/Current`
>   Update with: `brew install --cask xamarin-ios`

I followed the suggested workaround, but I’m still encountering `clang++` errors when building the project with a Sharpie binding library. The build fails with the following:

- `error: clang++ exited with code 1`

- `error: Undefined symbols for architecture arm64`

- `error: <initial-undefines>`

- `error: ld: symbol(s) not found for architecture arm64`

- `error: clang++: error: linker command failed with exit code 1`

Any guidance would be greatly appreciated. Thank you

**Comment by dalux-mka** [comment]
I am also having issues with this, are there any news or a workaround that does not involve writing the bindings manually? I tried the above suggestions but am still seeing the same errors.

**Comment by tompi** [comment]
> I am also having issues with this, are there any news or a workaround that does not involve writing the bindings manually? I tried the above suggestions but am still seeing the same errors.

Downgrading xcode to 16.2 should work, did you try that?

**Comment by dalux-mka** [comment]
Yes, I tried 16.2, 16.1 and 16.0.

**Comment by MDThomsen** [comment]
@rolfbjarne Hi, is there an update on this? I'm on .net 9.0.203 and have tried various xcode 16.* versions with the same problems

**Comment by rolfbjarne** [comment]
@MDThomsen no news for now, but other people have gotten Xcode 16.2 to work.

**Comment by arahmancsd** [comment]
facing the error after errors with iOS 18.5, Xcode 16.4. Apparently, the errors are similar to the question for WidgetBinding.

dotnet workload list output
maui                       9.0.82/9.0.100        SDK 9.0.100

**Comment by jonathanantoine** [comment]
It works with xCode 16.2 but you need to force the version of command line xcode (in Xcode settings : location then choose the correct one). Don't forget to restart the command line you are using sharpie in the first place too.

**Comment by rolfbjarne** [comment]
The first version of the new sharpie has been released: https://github.com/dotnet/macios/releases/tag/sharpie-26.3.0.11, so this should be fixed now.
