### ISSUE TITLE
Interfaces in ApiDefinitions.cs not visible to other classes

### ISSUE THREAD

**Issue by SaqibS** [dotnet/macios#22682]
### Framework version

net9.0-*

### Affected platform version

.NET 9.0.200

### Description

If I create a new bindings project (repro below), the types are not visible to other classes, even within the same project. And thus also not to classes in the main app project.

### Steps to Reproduce

* In an empty directory, create a new project with `dotnet new iosbinding`
* Create a new file, test.cs, with the following content:
  - `public interface ITest { void DoSomething(); }`
  - `public class Test { ITest T { get; set; } }`
* Build with `dotnet build -f net9.0-ios` and observe that it builds ok.
* Now, move the interface out of test.cs, but leave the class in test.cs. Paste the interface into ApiDefinitions.cs, and update test.cs to use the ApiDefinitions namespace.
* Now build with the same command, and you will get an error such as "test.cs: error CS0234: The type or namespace name 'ITest' does not exist in the namespace 'TestBinding' (are you missing an assembly reference?)".

### Did you find any workaround?

No
